# Use the Hacker theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Site info
title: Nabid Hasan's Portfolio
description: GNSS • 5G • RAN • Machine Learning • Cloud • Linux 

# Optional settings
show_downloads: false
