# Use the Hacker theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Site info
title: Nabidhn Portfolio
description: Digital Communication, SDR, RF, 5G projects

# Optional settings
show_downloads: false
